value:
  contact_rate: 0.076
  latent_period: 1.8
  infectious_period: 2.5
  natural_immunity_period: 60.0
  start_cdr: 0.3
  imm_prop: 0.4
  vacc_immune_period: 100.0
  imm_infect_protect: 0.4
  ifr_adjuster: 3.0
  ba1_seed_time: 619.0
  ba2_seed_time: 659.0
  ba5_seed_time: 715.0
  ba2_escape: 0.4
  ba5_escape: 0.54
  ba2_rel_ifr: 0.5
  wa_reopen_period: 50.0
  seed_duration: 10.0
  seed_rate: 1.0
  notifs_mean: 4.0
  notifs_shape: 2.0
  deaths_mean: 15.93
  deaths_shape: 5.0
  ifr_0: .NAN
  ifr_5: .NAN
  ifr_10: .NAN
  ifr_15: .NAN
  ifr_20: .NAN
  ifr_25: .NAN
  ifr_30: .NAN
  ifr_35: .NAN
  ifr_40: .NAN
  ifr_45: .NAN
  ifr_50: .NAN
  ifr_55: .NAN
  ifr_60: .NAN
  ifr_65: .NAN
  ifr_70: .NAN
  ifr_75: .NAN
descriptions:
  contact_rate: 'Effective contact rate'
  latent_period: 'Latent period'
  infectious_period: 'Infectious period'
  natural_immunity_period: 'Natural immunity period'
  start_cdr: 'Case detection rate'
  imm_prop: 'Proportion with increased immunity'
  vacc_immune_period: 'Post-vaccination period partial immunity'
  imm_infect_protect: 'Immunity infection protection'
  ifr_adjuster: 'Adjuster applied to all age-specific IFRs'
  ba1_seed_time: 'BA.1 seed start time'
  ba2_seed_time: 'BA.2 seed start time'
  ba5_seed_time: 'BA.5 seed start time'
  ba2_escape: 'BA.2 escape BA.1 immunity'
  ba5_escape: 'BA.5 escape BA.1 or BA.2 immunity'
  ba2_rel_ifr: 'Relative IFR for BA.2 compared to BA.1 and BA.5'
  wa_reopen_period: 'Time to WA fully mixing with rest of country'
  seed_duration: 'New variant seeding duration'
  seed_rate: 'New variant seeding rate'
  notifs_mean: 'Gamma distribution mean, infection to notification delay'
  notifs_shape: 'Gamma distribution shape, infection to notification delay'
  deaths_mean: 'Gamma distribution mean, infection to death delay'
  deaths_shape: 'Gamma distribution shape, infection to death delay'
  ifr_0: 'IFR, ages 0 to 4'
  ifr_5: 'IFR, ages 5 to 9'
  ifr_10: 'IFR, ages 10 to 14'
  ifr_15: 'IFR, ages 15 to 19'
  ifr_20: 'IFR, ages 20 to 24'
  ifr_25: 'IFR, ages 25 to 29'
  ifr_30: 'IFR, ages 30 to 34'
  ifr_35: 'IFR, ages 35 to 39'
  ifr_40: 'IFR, ages 40 to 44'
  ifr_45: 'IFR, ages 45 to 49'
  ifr_50: 'IFR, ages 50 to 54'
  ifr_55: 'IFR, ages 55 to 59'
  ifr_60: 'IFR, ages 60 to 64'
  ifr_65: 'IFR, ages 65 to 69'
  ifr_70: 'IFR, ages 70 to 74'
  ifr_75: 'IFR, ages 75 and above'
units:
  contact_rate: 'contacts per person per day'
  latent_period: 'days'
  infectious_period: 'days'
  natural_immunity_period: 'days'
  start_cdr: ''
  imm_prop: ''
  vacc_immune_period: 'days'
  imm_infect_protect: ''
  ifr_adjuster: ''
  ba1_seed_time: ''
  ba2_seed_time: ''
  ba5_seed_time: ''
  ba2_escape: ''
  ba5_escape: ''
  ba2_rel_ifr: ''
  wa_reopen_period: 'days'
  seed_duration: 'days'
  seed_rate: 'persons per day'
  notifs_mean: 'days'
  notifs_shape: ''
  deaths_mean: 'days'
  deaths_shape: ''
  ifr_0: ''
  ifr_5: ''
  ifr_10: ''
  ifr_15: ''
  ifr_20: ''
  ifr_25: ''
  ifr_30: ''
  ifr_35: ''
  ifr_40: ''
  ifr_45: ''
  ifr_50: ''
  ifr_55: ''
  ifr_60: ''
  ifr_65: ''
  ifr_70: ''
  ifr_75: ''
evidence:
  contact_rate: 'Calibrated within plausible range'
  latent_period: 'The shorter serial interval for Omicron compared to previous variants would also be consistent with a shorter latent period \cite{anderheiden2022, delaguilamejia2022, ito2022}. Transmission pairs were identified through contact tracing from an outbreak of BA.1.1 in Hangzhou (China) in early 2022, through which the latent period was estimated at 3.1 days \(95\% CI: 2.8-3.5\) \cite{xin2023}. The analysis used censoring to account for uncertainty in the time of infection and infectiousness onset from their data on time of contact with the assumed index case and the time of first positive PCR result.'
  infectious_period: 'Multiple studies have found a shorter serial interval or generation time for Omicron compared to previous variants \cite{anderheiden2022, delaguilamejia2022, ito2022, xin2023}, with values of five to seven days or less implying short latent and infectious periods. Taking duration of culturable virus as the best proxy for the infectious period, a systematic review and meta-analysis focused on the Omicron variant and reported the time from symptom onset or first positive PCR result to the day after the last positive viral culture to be 5.16 days \(95\% CI: 4.18-6.14\) \cite{wu2023}. We take this as an upper limit of the effective infectious duration because this quantity may be modified as symptomatic persons modify their behaviour to reduce contacts whilst infectious \cite{xin2023}.'
  natural_immunity_period: 'Early reinfection with SARS-CoV-2 is known to occur,\cite{nguyen2022} and antibodies against the virus decline significantly in the months following infection.\cite{denhartog2021,crawford2021} However, estimating the duration of natural immunity following infection with SARS-CoV-2 is challenging because reinfection due to the development of immune-escape properties in circulating viruses occurs contemporaneously with waning of immunity. An analysis of non-SARS-CoV-2 human coronaviruses that fitted a transmission model to positive laboratory test results estimated that immunity against infection waned over 45 weeks.\cite{kissler2020} Another analysis of non-SARS-CoV-2 human coronaviruses used antibody dynamics to conclude that reinfection typically occurred 12 months or more following past infection.\cite{edridge2020} However, an analysis of antibody dynamics for a range of human-infecting coronaviruses found that the duration of protection following SARS-CoV-2 infection was less than half of that of several other human-infecting coronaviruses, with reinfections likely occurring from as early as three months post-infection.\cite{townsend2021}'
  start_cdr: 'Calibrated across an uniform/uninformative but plausible range.'
  imm_prop: 'Allowed to vary through full range of possible values (zero to one) based on observation in model development that the sharpness of the BA.1 peak was more difficult to capture in the absence of heterogeneity in susceptibility.'
  vacc_immune_period: 'Neutralising antibody titres have been identified as key correlates of vaccine-derived immunological protection against infection with SARS-CoV-2.\cite{gilbert2022,feng2021,regev-yochay2023} However, neutralising antibodies and vaccine efficacy against infection with the wild-type virus were found to wane significantly over the first 250 days following vaccination.\cite{khoury2021} More recently, whilst an initial booster with a third monovalent wild-type mRNA vaccine dose produced a considerable increase in neutralising antibody titres against Omicron, the neutralising antibody response waned significantly by 3-4 months.\cite{gilboa2022, wilhelm2022} Observational studies have similarly demonstrated that, following a third monovalent booster, vaccine effectiveness against infection with Omicron waned significantly over 3-4 months.\cite{patalon2022} A prospective cohort study of healthcare workers in Israel demonstrated similar neutralising antibody titre and waning profiles following third and fourth doses.\cite{canetti2022} Similar to a third booster dose, observational data have suggested that a fourth dose provides about 3-4 months of protection against infection before waning.\cite{bar-on2022} To accommodate these lines of evidence, we chose a prior distribution that broadly spanned conditions under which the bulk of vaccine-derived immunity against infection was lost within 3-4 months (also noting that the modelled vaccination program is lagged by 14 days to allow for the development of immunity).'
  imm_infect_protect: 'Allowed to vary through full range of possible values (zero to one) based on observation in model development that the sharpness of the BA.1 peak was more difficult to capture in the absence of heterogeneity in susceptibility.'
  ifr_adjuster: 'Adjustment applied to all age-specific base IFR estimates, see \ref{infection_fatality_rates}.'
  ba1_seed_time: 'Calibrated within range that produces model outputs consistent with national sequencing data.'
  ba2_seed_time: 'Calibrated within range that produces model outputs consistent with national sequencing data.'
  ba5_seed_time: 'Calibrated within range that produces model outputs consistent with national sequencing data.'
  ba2_escape: 'BA.2 appears to be a significant immune-escape variant to previous strains of SARS-CoV-2, including past BA.1 infection. A single past BA.1 infection induces markedly lower titres of neutralising antibodies against BA.2 than does a past BA.2 infection.\cite{rossler2022} A test-negative case-control study of health care workers in Quebec found a 72\% (95\% CI 65-78) reduction in risk of SARS-CoV-2 infection for those previously infected with BA.1 in unvaccinated participants during a period of predominant BA.2 transmission, \cite{carazo2023} although indication for testing differed markedly between cases and controls. Another test-negative case-control study conducted in adolescents in the UK during the BA.1 and BA.2 periods found that previous Omicron infection conferred 59.3\% (95\% CI 46.7-69.0) protection against Omicron reinfection in the unvaccinated.\cite{powell2023} Although this figure does not distinguish between sub-variants, this analysis is likely to include many BA.2 reinfections following previous BA.1 infection. A third estimate from the highly vaccinated population of Qatar found very high levels of protection 94.2\% (95\% CI 89.2-96.9) against BA.2 reinfection from past BA.1 infection, although follow-up was relatively short.\cite{chemaitelly2022a} For all of these studies, distinguishing between waning with immunity with time and escape properties of the virus are extremely hard to disentangle. We note that in addition to Australia several other settings have observed BA.2 waves that have followed closely on the heels of a declining BA.1 epidemic, including the UK, France and the Netherlands.\cite{elliott2022} This could suggest significant immune escape properties of BA.2 against BA.1 immunity or a markedly greater reproduction number. Given the extremely infectious nature of all Omicron strains, the former seems more epidemiologically plausible.'
  ba5_escape: 'BA.5 again shows significant immune-escape to previous SARS-CoV-2 variants, including BA.1 and BA.2, with lower levels of neutralising antibodies generated against BA.5 from past BA.1 infection than for BA.2 infection.\cite{rossler2022} The loss of neutralisation activity against BA.5 following a BA.1 infection appears greater in unvaccinated than vaccinated persons.\cite{khan2022} Significant immune evasion of BA.5 against prior Omicron subvariant infection is suggested by the UK’s ONS infection survey, which found that 54\% of BA.5 reinfections had their first infection during the BA.1 or BA.2 waves.\cite{onssurvey2023} Observational studies have estimated the real-world protection against BA.5 reinfection conferred by prior BA.1 or BA.2 infection. Portugal was one of the first countries to be affected by the BA.5 subvariant, only a few months after a major mixed BA.1 and BA.2 epidemic. Infection with BA.1 or BA.2 was estimated to confer 75.3\% protection against BA.5 infection, which was somewhat greater than for previous variants (e.g. Delta 61.3\% protection).\cite{malato2022b} The authors note a perception of very low protection of past BA.1/BA.2 infection against BA.5, but attribute this to moderate protection in a setting with a high attack rate from the recent BA.1/BA.2 wave. A national test-negative case-control study in Qatar similarly found that prior infection with BA.1 or BA.2 was 68.7\% effective in preventing reinfection in the unvaccinated.\cite{altarawneh2022b} A retrospective cohort study from Singapore found no protection against BA.4/5 infection was conferred from prior BA.1/2 infection, although vaccination status differed markedly from the previously infected and infection-naive groups.\cite{tan2023} Although not directly applicable to this parameter, these findings are consistent with substantial immune escape. A limitation of these three studies \cite{malato2022b, altarawneh2022b, tan2023} is that they leverage passive surveillance data and so may underestimate the true number of infections, particularly asymptomatic or pauci-symptomatic infections and hence underestimate the extent of immune escape. Prospective household contact transmission studies with an active surveillance strategy may better estimate the effect of prior infection,\cite{miller2021} but were unavailable for the variants considered here.'
  ba2_rel_ifr: 'Two national-level studies estimated the severity of BA.2 relative to BA.1 using the time period of the epidemic combined with PCR S-gene target failure status to identify cases of each sub-variant. In the United Kingdom, the hazard ratio for death was estimated at 0.80 (95\%CI 0.71-0.90) for BA.2 compared to BA.1.\cite{webster2022} Although a large South African study did not estimate the relative risk of death, the adjusted odds ratio for a composite severe disease outcome was comparable to this estimate (0.78, 95\%CI 0.63-0.97) \cite{wolter2022}. A nationwide study from Denmark \cite{hansen2023} leveraged high coverage with PCR testing and whole-genome sequencing to estimate the odds of hospitalisation with BA.5 relative to BA.2, estimating an adjusted odds ratio of 1.69 (95\%CI 1.22-2.33). An analysis from Scotland was consistent with a comparably increased adjusted hazard of hospitalisation (1.21, 95\%CI 1.03, 1.43) and death (1.55, 95\%CI 0.78-3.08), although with a broad uncertainty ranges.\cite{robertson2023} Although these estimates comparing BA.5 to BA.2 may suggest a greater difference in severity than between BA.1 and BA.2, the South African analysis found no difference in severity between BA.1 and BA.5.\cite{wolter2022}'
  wa_reopen_period: 'Although the Western Australia (WA) Government re-opened borders from 3rd March 2022, some restrictions initially remained in place after this date, including the requirement for a rapid antigen test on arrival into the state.\cite{wagov2022} Further, domestic air travel into the WA remained below pre-Covid levels until around mid-year 2022.\cite{bitre2023} More importantly, the modelled assumption of homogeneous mixing within population age groups means that it would be unrealistic that the population of WA would be subject to the same force of infection as other Australian jurisdictions immediately from the date of re-opening. For this reason, we scale up the rate of infection in WA to reach the same level as the remainder of the country over a period of time that is varied through calibration.Although the Western Australia (WA) Government re-opened borders from 3rd March 2022, some restrictions initially remained in place after this date, including the requirement for a rapid antigen test on arrival into the state.\cite{wagov2022} Further, domestic air travel into the WA remained below pre-Covid levels until around mid-year 2022 and was relatively lower than other Australian states until April-May 2022.\cite{bitre2023} More importantly, the modelled assumption of homogeneous mixing within population age groups means that it would be unrealistic to assume that the population of WA would be subject to the same force of infection as other Australian jurisdictions immediately from the date of re-opening. For this reason, we scale up the rate of infection in WA to reach the same level as the remainder of the country over a period of time that is consistent with a mid-year epidemic.'
  seed_duration: 'Arbitrarily set to a low value to introduce new sub-variant.'
  seed_rate: 'Arbitrarily set to a low value to introduce new sub-variant.'
  notifs_mean: 'By contrast to the time from symptom onset to death, which we consider to be more a biological phenomenon intrinsic to the pathogen, we searched for locally applicable estimates to inform the delay from symptom onset to case notification. A published analysis estimating the transmission potential in Australia from February 2020 to February 2021\cite{golding2023} provided publicly accessible data on the number of days from symptom onset to notification in Victoria and New South Wales. From these data we calculated a mean delay from symptom onset to notification of 4.17 days.'
  notifs_shape: 'Estimated from plotting distribution of notification data.\cite{golding2023}'
  deaths_mean: 'A cohort of patients presenting to two central Wuhan hospitals early in the pandemic estimated a mode of 14 days for time from symptom onset to death,\cite{ruan2020} while a study of case presentations outside of the Wuhan epicentre estimated a mean of 20.2 days (95\% CI 7.4-39.9) when right truncation was accounted for.\cite{linton2020} These two studies were combined with a second Wuhan cohort \cite{shi2020} (likely overlapping with the first Wuhan study\cite{ruan2020}) in a meta-analysis\cite{khalili2020} that estimated the mean time to death at 15.93 days (95\% CI 13.07-18.79). An analysis of Victorian data from 2020 estimated the mean time from diagnosis to death at 18.1 days (95\% CI 16.9-19.3), which varied little by age.\cite{marschner2021} Although fewer estimates were found for the Omicron period, and despite the clearly lower fatality rate for Omicron than for Delta, a study of adults in the UK from December 2021 found the same mean delay from testing positive to death for Omicron BA.1 as for Delta (18 days).\cite{ward2022}'
  deaths_shape: 'A shape parameter of five appeared to broadly reproduce the distribution of deaths presented in the first Wuhan cohort \cite{ruan2020} and the upper centiles reported in the non-Wuhan Chinese presentations analysis.\cite{linton2020}'
  ifr_0: 'See Section \ref{infection_fatality_rates} text.'
  ifr_5: 'See Section \ref{infection_fatality_rates} text.'
  ifr_10: 'See Section \ref{infection_fatality_rates} text.'
  ifr_15: 'See Section \ref{infection_fatality_rates} text.'
  ifr_20: 'See Section \ref{infection_fatality_rates} text.'
  ifr_25: 'See Section \ref{infection_fatality_rates} text.'
  ifr_30: 'See Section \ref{infection_fatality_rates} text.'
  ifr_35: 'See Section \ref{infection_fatality_rates} text.'
  ifr_40: 'See Section \ref{infection_fatality_rates} text.'
  ifr_45: 'See Section \ref{infection_fatality_rates} text.'
  ifr_50: 'See Section \ref{infection_fatality_rates} text.'
  ifr_55: 'See Section \ref{infection_fatality_rates} text.'
  ifr_60: 'See Section \ref{infection_fatality_rates} text.'
  ifr_65: 'See Section \ref{infection_fatality_rates} text.'
  ifr_70: 'See Section \ref{infection_fatality_rates} text.'
  ifr_75: 'See Section \ref{infection_fatality_rates} text.'
abbreviations:
  contact_rate: 'Contact rate'
  latent_period: 'Latent period'
  infectious_period: 'Infectious period'
  natural_immunity_period: 'Immune period'
  start_cdr: 'CDR'
  imm_prop: 'Prop immune'
  vacc_immune_period: 'Vacc immune period'
  imm_infect_protect: 'Immune protection'
  ifr_adjuster: 'IFR adjuster'
  ba1_seed_time: 'BA.1 seed'
  ba2_seed_time: 'BA.2 seed'
  ba5_seed_time: 'BA.5 seed'
  ba2_escape: 'BA.2 escape'
  ba5_escape: 'BA.5 escape'
  ba2_rel_ifr: 'BA.2 rel IFR'
  wa_reopen_period: 'WA reopen period'
  seed_duration: 'Seed time'
  seed_rate: 'Seed rate'
  notifs_mean: 'Notif delay mean'
  notifs_shape: 'Notif delay shape'
  deaths_mean: 'Death delay mean'
  deaths_shape: 'Death delay shape'
  ifr_0: 'IFR 0-4'
  ifr_5: 'IFR 5-9'
  ifr_10: 'IFR 10-14'
  ifr_15: 'IFR 15-19'
  ifr_20: 'IFR 20-24'
  ifr_25: 'IFR 25-29'
  ifr_30: 'IFR 30-34'
  ifr_35: 'IFR 35-39'
  ifr_40: 'IFR 40-44'
  ifr_45: 'IFR 45-49'
  ifr_50: 'IFR 50-54'
  ifr_55: 'IFR 55-59'
  ifr_60: 'IFR 60-64'
  ifr_65: 'IFR 65-69'
  ifr_70: 'IFR 70-74'
  ifr_75: 'IFR 75+'