descriptions:
  contact_rate: "Rate of effective contacts"
  infectious_period: "Infectious period"
  latent_period: "Latent period"
  full_immune_period: "Post-infection period of high immunity"
  cdr: "Case detection rate (proportion of infections captured through surveillance)"
  seed_rate: "Rate of introduction of persons infected with each new variant"
  seed_duration: "Duration of introduction of persons infected with each new variant"
  ba2_rel_infness: "Relative infectiousness of BA.2 relative to BA.1"
  ba1_seed_time: "Time BA.1 infectious seed begins"
  ba2_seed_time: "Time BA.2 infectious seed begins"
  ba5_seed_time: "Time BA.5 infectious seed begins"
  ba2_escape: "BA.2 escape from natural immunity from BA.1 infection"
  ba5_escape: "BA.5 escape from natural immunity from BA.1 or BA.2 infection"
units:
  contact_rate: "contacts per person per day"
  infectious_period: "days"
  latent_period: "days"
  full_immune_period: "days"
  cdr: ""
  seed_rate: "persons per day"
  seed_duration: "days"
  ba2_rel_infness: ""
  ba1_seed_time: ""
  ba2_seed_time: ""
  ba5_seed_time: ""
  ba2_escape: ""
  ba5_escape: ""
evidence:
  contact_rate: "Calibrated within plausible range"
  infectious_period: "This quantity is difficult to estimate, given that identified cases are typically quarantined. Studies in settings of high case ascertainment and an effective public health response have suggested a duration of greater than 5.5 days \\cite{bi2020}. PCR positivity, which may continue for up to two to three weeks from the point of symptom onset \\cite{he2020} \\cite{byrne2020} does not necessarily indicate infectiousness. The duration infectious for asymptomatic persons has also been estimated at 6.5 to 9.5 days \\cite{byrne2020}."
  latent_period: "Assumed"
  full_immune_period: "Assumed"
  cdr: "Assumed"
  seed_rate: "Assumed"
  seed_duration: "Assumed"
  ba2_rel_infness: "Assumed"
  ba1_seed_time: "Assumed"
  ba2_seed_time: "Assumed"
  ba5_seed_time: "Assumed"
  ba2_escape: "Assumed"
  ba5_escape: "Assumed"