descriptions:
  contact_rate: 'Effective contact rate'
  latent_period: 'Latent period'
  infectious_period: 'Infectious period'
  natural_immunity_period: 'Natural immunity period'
  start_cdr: 'Case detection rate'
  vacc_prop: 'Proportion vaccinated'
  vacc_infect_protect: 'Vaccination infection protection'
  ifr_adjuster: 'Adjuster applied to all age-specific IFRs'
  ba1_seed_time: 'BA.1 seed start time'
  ba2_seed_time: 'BA.2 seed start time'
  ba5_seed_time: 'BA.5 seed start time'
  ba2_escape: 'BA.2 escape BA.1 immunity'
  ba5_escape: 'BA.5 escape BA.1 or BA.2 immunity'
  ba2_rel_ifr: 'Relative IFR for BA.2 compared to BA.1 and BA.5'
  wa_reopen_period: 'Time to WA fully mixing with rest of country'
  seed_duration: 'New variant seeding duration'
  seed_rate: 'New variant seeding rate'
  notifs_shape: 'Gamma distribution shape, infection to notification delay'
  notifs_mean: 'Gamma distribution mean, infection to notification delay'
  deaths_shape: 'Gamma distribution shape, infection to death delay'
  deaths_mean: 'Gamma distribution mean, infection to death delay'
  ifr_0: 'IFR, ages 0 to 4'
  ifr_5: 'IFR, ages 5 to 9'
  ifr_10: 'IFR, ages 10 to 14'
  ifr_15: 'IFR, ages 15 to 19'
  ifr_20: 'IFR, ages 20 to 24'
  ifr_25: 'IFR, ages 25 to 29'
  ifr_30: 'IFR, ages 30 to 34'
  ifr_35: 'IFR, ages 35 to 39'
  ifr_40: 'IFR, ages 40 to 44'
  ifr_45: 'IFR, ages 45 to 49'
  ifr_50: 'IFR, ages 50 to 54'
  ifr_55: 'IFR, ages 55 to 59'
  ifr_60: 'IFR, ages 60 to 64'
  ifr_65: 'IFR, ages 65 to 69'
  ifr_70: 'IFR, ages 70 to 74'
  ifr_75: 'IFR, ages 75 and above'
units:
  contact_rate: 'contacts per person per day'
  latent_period: 'days'
  infectious_period: 'days'
  natural_immunity_period: 'days'
  start_cdr: ''
  vacc_prop: ''
  vacc_infect_protect: ''
  ifr_adjuster: ''
  ba1_seed_time: ''
  ba2_seed_time: ''
  ba5_seed_time: ''
  ba2_escape: ''
  ba5_escape: ''
  ba2_rel_ifr: ''
  wa_reopen_period: 'days'
  seed_duration: 'days'
  seed_rate: 'persons per day'
  notifs_shape: ''
  notifs_mean: 'days'
  deaths_shape: ''
  deaths_mean: 'days'
  ifr_0: ''
  ifr_5: ''
  ifr_10: ''
  ifr_15: ''
  ifr_20: ''
  ifr_25: ''
  ifr_30: ''
  ifr_35: ''
  ifr_40: ''
  ifr_45: ''
  ifr_50: ''
  ifr_55: ''
  ifr_60: ''
  ifr_65: ''
  ifr_70: ''
  ifr_75: ''
evidence:
  contact_rate: 'Calibrated within plausible range'
  latent_period: 'The shorter serial interval for Omicron compared to previous variants would also be consistent with a shorter latent period \cite{anderheiden2022, delaguilamejia2022, ito2022}. Transmission pairs were identified through contact tracing from an outbreak of BA.1.1 in Hangzhou (China) in early 2022, through which the latent period was estimated at 3.1 days \(95\% CI: 2.8-3.5\) \cite{xin2023}. The analysis used censoring to account for uncertainty in the time of infection and infectiousness onset from their data on time of contact with the assumed index case and the time of first positive PCR result.'
  infectious_period: 'Multiple studies have found a shorter serial interval or generation time for Omicron compared to previous variants \cite{anderheiden2022, delaguilamejia2022, ito2022, xin2023}, with values of five to seven days or less implying short latent and infectious periods. Taking duration of culturable virus as the best proxy for the infectious period, a systematic review and meta-analysis focused on the Omicron variant and reported the time from symptom onset or first positive PCR result to the day after the last positive viral culture to be 5.16 days \(95\% CI: 4.18-6.14\) \cite{wu2023}. We take this as an upper limit of the effective infectious duration because this quantity may be modified as symptomatic persons modify their behaviour to reduce contacts whilst infectious \cite{xin2023}.'
  natural_immunity_period: 'Although early reinfection with SARS-CoV-2 occurs,\cite{nguyen2022} estimating the duration of natural immunity following infection with SARS-CoV-2 is challenging because reinfection due to the development of immune-escape properties in circulating viruses occurs contemporaneously with waning of immunity. An analysis of non-SARS-CoV-2 human coronaviruses that fitted a transmission model to positive laboratory test results estimated that immunity against infection waned over 45 weeks.\cite{kissler2020} Another analysis of non-SARS-CoV-2 human coronaviruses used antibody dynamics to conclude that reinfection typically occurred 12 months or more following past infection.\cite{edridge2020} However, an analysis of antibody dynamics for a range of human-infecting coronaviruses found that the duration of protection following SARS-CoV-2 infection was less than half of that of several other human-infecting coronaviruses, with reinfections likely occurring from as early as three months post-infection.\cite{townsend2021}Early reinfection with SARS-CoV-2 is known to occur,\cite{nguyen2022} and antibodies against the virus decline significantly in the months following infection.\cite{denhartog2021,crawford2021} However, estimating the duration of natural immunity following infection with SARS-CoV-2 is challenging because reinfection due to the development of immune-escape properties in circulating viruses occurs contemporaneously with waning of immunity. An analysis of non-SARS-CoV-2 human coronaviruses that fitted a transmission model to positive laboratory test results estimated that immunity against infection waned over 45 weeks.\cite{kissler2020} Another analysis of non-SARS-CoV-2 human coronaviruses used antibody dynamics to conclude that reinfection typically occurred 12 months or more following past infection.\cite{edridge2020} However, an analysis of antibody dynamics for a range of human-infecting coronaviruses found that the duration of protection following SARS-CoV-2 infection was less than half of that of several other human-infecting coronaviruses, with reinfections likely occurring from as early as three months post-infection.\cite{townsend2021}'
  start_cdr: 'Calibrated across an uniform/uninformative but plausible range.'
  vacc_prop: 'Assumed'
  vacc_infect_protect: 'Assumed'
  ifr_adjuster: 'Adjustment applied to all age-specific base IFR estimates, see \ref{infection_fatality_rates}.'
  ba1_seed_time: 'Calibrated within range that produces model outputs consistent with national sequencing data.'
  ba2_seed_time: 'Calibrated within range that produces model outputs consistent with national sequencing data.'
  ba5_seed_time: 'Calibrated within range that produces model outputs consistent with national sequencing data.'
  ba2_escape: 'Assumed'
  ba5_escape: 'Assumed'
  ba2_rel_ifr: 'Two national-level studies estimated the severity of BA.2 relative to BA.1 using the time period of the epidemic combined with PCR S-gene target failure status to identify cases of each sub-variant. In the United Kingdom, the hazard ratio for death was estimated at 0.80 (95\%CI 0.71-0.90) for BA.2 compared to BA.1.\cite{webster2022} Although a large South African study did not estimate the relative risk of death, the adjusted odds ratio for a composite severe disease outcome was comparable to this estimate (0.78, 95\%CI 0.63-0.97) \cite{wolter2022}. A nationwide study from Denmark \cite{hansen2023} leveraged high coverage with PCR testing and whole-genome sequencing to estimate the odds of hospitalisation with BA.5 relative to BA.2, estimating an adjusted odds ratio of 1.69 (95\%CI 1.22-2.33). An analysis from Scotland was consistent with a comparably increased adjusted hazard of hospitalisation (1.21, 95\%CI 1.03, 1.43) and death (1.55, 95\%CI 0.78-3.08), although with a broad uncertainty ranges.\cite{robertson2023} Although these estimates comparing BA.5 to BA.2 may suggest a greater difference in severity than between BA.1 and BA.2, the South African analysis found no difference in severity between BA.1 and BA.5.\cite{wolter2022}'
  wa_reopen_period: 'Although the Western Australia (WA) Government re-opened borders from 3rd March 2022, some restrictions initially remained in place after this date, including the requirement for a rapid antigen test on arrival into the state.\cite{wagov2022} Further, domestic air travel into the WA remained below pre-Covid levels until around mid-year 2022.\cite{bitre2023} More importantly, the modelled assumption of homogeneous mixing within population age groups means that it would be unrealistic that the population of WA would be subject to the same force of infection as other Australian jurisdictions immediately from the date of re-opening. For this reason, we scale up the rate of infection in WA to reach the same level as the remainder of the country over a period of time that is varied through calibration.'
  seed_duration: 'Arbitrarily set to a low value to introduce new sub-variant.'
  seed_rate: 'Arbitrarily set to a low value to introduce new sub-variant.'
  notifs_shape: 'Assumed'
  notifs_mean: 'Assumed'
  deaths_shape: 'A shape parameter of five appeared to broadly reproduce the distribution of deaths presented in the first Wuhan cohort \cite{ruan2020} and the upper centiles reported in the non-Wuhan Chinese presentations analysis.\cite{linton2020}'
  deaths_mean: 'A cohort of patients presenting to two central Wuhan hospitals early in the pandemic estimated a mode of 14 days for time from symptom onset to death,\cite{ruan2020} while a study of case presentations outside of the Wuhan epicentre estimated a mean of 20.2 days (95\% CI 7.4-39.9) when right truncation was accounted for.\cite{linton2020} These two studies were combined with a second Wuhan cohort \cite{shi2020} (likely overlapping with the first Wuhan study\cite{ruan2020}) in a meta-analysis\cite{kahlili2020} that estimated the mean time to death at 15.93 days (95\% CI 13.07-18.79). An analysis of Victorian data from 2020 estimated the mean time from diagnosis to death at 18.1 days (95\% CI 16.9-19.3), which varied little by age.\cite{marschner2021} Although fewer estimates were found for the Omicron period, and despite the clearly lower fatality rate for Omicron than for Delta, a study of adults in the UK from December 2021 found the same mean delay from testing positive to death for Omicron BA.1 as for Delta (18 days).\cite{ward2022}'
  ifr_0: 'See Section \ref{infection_fatality_rates} text.'
  ifr_5: 'See Section \ref{infection_fatality_rates} text.'
  ifr_10: 'See Section \ref{infection_fatality_rates} text.'
  ifr_15: 'See Section \ref{infection_fatality_rates} text.'
  ifr_20: 'See Section \ref{infection_fatality_rates} text.'
  ifr_25: 'See Section \ref{infection_fatality_rates} text.'
  ifr_30: 'See Section \ref{infection_fatality_rates} text.'
  ifr_35: 'See Section \ref{infection_fatality_rates} text.'
  ifr_40: 'See Section \ref{infection_fatality_rates} text.'
  ifr_45: 'See Section \ref{infection_fatality_rates} text.'
  ifr_50: 'See Section \ref{infection_fatality_rates} text.'
  ifr_55: 'See Section \ref{infection_fatality_rates} text.'
  ifr_60: 'See Section \ref{infection_fatality_rates} text.'
  ifr_65: 'See Section \ref{infection_fatality_rates} text.'
  ifr_70: 'See Section \ref{infection_fatality_rates} text.'
  ifr_75: 'See Section \ref{infection_fatality_rates} text.'