descriptions:
  contact_rate: 'Effective contact rate'
  infectious_period: 'Infectious period'
  latent_period: 'Latent period'
  start_cdr: 'Case detection rate'
  seed_rate: 'New variant seeding rate'
  seed_duration: 'New variant seeding duration'
  ba1_seed_time: 'BA.1 seed start time'
  ba2_seed_time: 'BA.2 seed start time'
  ba5_seed_time: 'BA.5 seed start time'
  ba2_escape: 'BA.2 escape BA.1 immunity'
  ba5_escape: 'BA.5 escape BA.1 or BA.2 immunity'
  notifs_shape: 'Gamma distribution shape, infection to notification delay'
  notifs_mean: 'Gamma distribution mean, infection to notification delay'
  natural_immunity_period: 'Natural immunity period'
  vacc_infect_protect: 'Vaccination infection protection'
  vacc_prop: 'Proportion vaccinated'
  wa_reopen_period: 'Time to WA fully mixing with rest of country'
  deaths_shape: 'Gamma distribution shape, infection to death delay'
  deaths_mean: 'Gamma distribution mean, infection to death delay'
  ifr_0: 'IFR, ages 0 to 4'
  ifr_5: 'IFR, ages 5 to 9'
  ifr_10: 'IFR, ages 10 to 14'
  ifr_15: 'IFR, ages 15 to 19'
  ifr_20: 'IFR, ages 20 to 24'
  ifr_25: 'IFR, ages 25 to 29'
  ifr_30: 'IFR, ages 30 to 34'
  ifr_35: 'IFR, ages 35 to 39'
  ifr_40: 'IFR, ages 40 to 44'
  ifr_45: 'IFR, ages 45 to 49'
  ifr_50: 'IFR, ages 50 to 54'
  ifr_55: 'IFR, ages 55 to 59'
  ifr_60: 'IFR, ages 60 to 64'
  ifr_65: 'IFR, ages 65 to 69'
  ifr_70: 'IFR, ages 70 to 74'
  ifr_75: 'IFR, ages 75 and above'
  ifr_adjuster: 'Adjuster applied to all age-specific IFRs'
  ba2_rel_ifr: 'Relative IFR for BA.2 compared to BA.1 and BA.5'
units:
  contact_rate: 'contacts per person per day'
  infectious_period: 'days'
  latent_period: 'days'
  start_cdr: ''
  seed_rate: 'persons per day'
  seed_duration: 'days'
  ba1_seed_time: ''
  ba2_seed_time: ''
  ba5_seed_time: ''
  ba2_escape: ''
  ba5_escape: ''
  notifs_shape: ''
  notifs_mean: 'days'
  natural_immunity_period: 'days'
  vacc_infect_protect: ''
  vacc_prop: ''
  wa_reopen_period: 'days'
  deaths_shape: ''
  deaths_mean: 'days'
  ifr_0: ''
  ifr_5: ''
  ifr_10: ''
  ifr_15: ''
  ifr_20: ''
  ifr_25: ''
  ifr_30: ''
  ifr_35: ''
  ifr_40: ''
  ifr_45: ''
  ifr_50: ''
  ifr_55: ''
  ifr_60: ''
  ifr_65: ''
  ifr_70: ''
  ifr_75: ''
  ifr_adjuster: ''
  ba2_rel_ifr: ''
evidence:
  contact_rate: 'Calibrated within plausible range'
  infectious_period: 'Multiple studies have found a shorter serial interval or generation time for Omicron compared to previous variants \cite{anderheiden2022, delaguilamejia2022, ito2022, xin2023}, with values of five to seven days or less implying short latent and infectious periods. Taking duration of culturable virus as the best proxy for the infectious period, a systematic review and meta-analysis focused on the Omicron variant and reported the time from symptom onset or first positive PCR result to the day after the last positive viral culture to be 5.16 days \(95\% CI: 4.18-6.14\) \cite{wu2023}. We take this as an upper limit of the effective infectious duration because this quantity may be modified as symptomatic persons modify their behaviour to reduce contacts whilst infectious \cite{xin2023}.'
  latent_period: 'The shorter serial interval for Omicron compared to previous variants would also be consistent with a shorter latent period \cite{anderheiden2022, delaguilamejia2022, ito2022}. Transmission pairs were identified through contact tracing from an outbreak of BA.1.1 in Hangzhou (China) in early 2022, through which the latent period was estimated at 3.1 days \(95\% CI: 2.8-3.5\) \cite{xin2023}. The analysis used censoring to account for uncertainty in the time of infection and infectiousness onset from their data on time of contact with the assumed index case and the time of first positive PCR result.'
  start_cdr: ''
  seed_rate: 'Assumed'
  seed_duration: 'Assumed'
  ba1_seed_time: 'Assumed'
  ba2_seed_time: 'Assumed'
  ba5_seed_time: 'Assumed'
  ba2_escape: 'Assumed'
  ba5_escape: 'Assumed'
  notifs_shape: 'Assumed'
  notifs_mean: 'Assumed'
  natural_immunity_period: 'Assumed'
  vacc_infect_protect: 'Assumed'
  vacc_prop: 'Assumed'
  wa_reopen_period: 'Assumed'
  deaths_shape: 'Assumed'
  deaths_mean: 'Assumed'
  ifr_0: 'See Section \ref{infection_fatality_rates} text.'
  ifr_5: 'See Section \ref{infection_fatality_rates} text.'
  ifr_10: 'See Section \ref{infection_fatality_rates} text.'
  ifr_15: 'See Section \ref{infection_fatality_rates} text.'
  ifr_20: 'See Section \ref{infection_fatality_rates} text.'
  ifr_25: 'See Section \ref{infection_fatality_rates} text.'
  ifr_30: 'See Section \ref{infection_fatality_rates} text.'
  ifr_35: 'See Section \ref{infection_fatality_rates} text.'
  ifr_40: 'See Section \ref{infection_fatality_rates} text.'
  ifr_45: 'See Section \ref{infection_fatality_rates} text.'
  ifr_50: 'See Section \ref{infection_fatality_rates} text.'
  ifr_55: 'See Section \ref{infection_fatality_rates} text.'
  ifr_60: 'See Section \ref{infection_fatality_rates} text.'
  ifr_65: 'See Section \ref{infection_fatality_rates} text.'
  ifr_70: 'See Section \ref{infection_fatality_rates} text.'
  ifr_75: 'See Section \ref{infection_fatality_rates} text.'
  ifr_adjuster: 'Adjustment applied to all age-specific base IFR estimates, see \ref{infection_fatality_rates}.'
  ba2_rel_ifr: 'Assumed'