descriptions:
  contact_rate: "Rate of effective contacts"
  infectious_period: "Infectious period"
  latent_period: "Latent period"
  full_immune_period: "Post-infection period of high immunity"
  cdr: "Case detection rate (proportion of infections captured through surveillance)"
  seed_rate: "Rate of introduction of persons infected with each new variant"
  seed_duration: "Duration of introduction of persons infected with each new variant"
  ba2_rel_infness: "Relative infectiousness of BA.2 relative to BA.1"
  ba1_seed_time: "Time BA.1 infectious seed begins"
  ba2_seed_time: "Time BA.2 infectious seed begins"
  ba5_seed_time: "Time BA.5 infectious seed begins"
  ba2_escape: "BA.2 escape from natural immunity from BA.1 infection"
  ba5_escape: "BA.5 escape from natural immunity from BA.1 or BA.2 infection"
  notifs_shape: "Shape of gamma distribution for infection to notification function"
  notifs_mean: "Mean of gamma distribution for infection to notification function"
  deaths_shape: "Shape of gamma distribution for infection to death function"
  deaths_mean: "Mean of gamma distribution for infection to death function"
  natural_immunity_period: "Average period with natural immunity against reinfection"
  ifr_0: "Infection fatality rate, ages 0 to 4"
  ifr_5: "Infection fatality rate, ages 5 to 9"
  ifr_10: "Infection fatality rate, ages 10 to 14"
  ifr_15: "Infection fatality rate, ages 15 to 19"
  ifr_20: "Infection fatality rate, ages 20 to 24"
  ifr_25: "Infection fatality rate, ages 25 to 29"
  ifr_30: "Infection fatality rate, ages 30 to 34"
  ifr_35: "Infection fatality rate, ages 35 to 39"
  ifr_40: "Infection fatality rate, ages 40 to 44"
  ifr_45: "Infection fatality rate, ages 45 to 49"
  ifr_50: "Infection fatality rate, ages 50 to 54"
  ifr_55: "Infection fatality rate, ages 55 to 59"
  ifr_60: "Infection fatality rate, ages 60 to 64"
  ifr_65: "Infection fatality rate, ages 65 to 69"
  ifr_70: "Infection fatality rate, ages 70 to 74"
units:
  contact_rate: "contacts per person per day"
  infectious_period: "days"
  latent_period: "days"
  full_immune_period: "days"
  cdr: ""
  seed_rate: "persons per day"
  seed_duration: "days"
  ba2_rel_infness: ""
  ba1_seed_time: ""
  ba2_seed_time: ""
  ba5_seed_time: ""
  ba2_escape: ""
  ba5_escape: ""
  notifs_shape: ""
  notifs_mean: "days"
  deaths_shape: ""
  deaths_mean: "days"
  natural_immunity_period: "days"
  ifr_0: ""
  ifr_5: ""
  ifr_10: ""
  ifr_15: ""
  ifr_20: ""
  ifr_25: ""
  ifr_30: ""
  ifr_35: ""
  ifr_40: ""
  ifr_45: ""
  ifr_50: ""
  ifr_55: ""
  ifr_60: ""
  ifr_65: ""
  ifr_70: ""
evidence:
  contact_rate: "Calibrated within plausible range"
  infectious_period: "This quantity is difficult to estimate, given that identified cases are typically quarantined. Studies in settings of high case ascertainment and an effective public health response have suggested a duration of greater than 5.5 days \\cite{bi2020}. PCR positivity, which may continue for up to two to three weeks from the point of symptom onset \\cite{he2020} \\cite{byrne2020} does not necessarily indicate infectiousness. The duration infectious for asymptomatic persons has also been estimated at 6.5 to 9.5 days \\cite{byrne2020}."
  latent_period: "Assumed"
  full_immune_period: "Assumed"
  cdr: "Assumed"
  seed_rate: "Assumed"
  seed_duration: "Assumed"
  ba2_rel_infness: "Assumed"
  ba1_seed_time: "Assumed"
  ba2_seed_time: "Assumed"
  ba5_seed_time: "Assumed"
  ba2_escape: "Assumed"
  ba5_escape: "Assumed"
  notifs_shape: "Assumed"
  notifs_mean: "Assumed"
  deaths_shape: "Assumed"
  deaths_mean: "Assumed"
  natural_immunity_period: "Assumed"
  ifr_0: "Assumed"
  ifr_5: "Assumed"
  ifr_10: "Assumed"
  ifr_15: "Assumed"
  ifr_20: "Assumed"
  ifr_25: "Assumed"
  ifr_30: "Assumed"
  ifr_35: "Assumed"
  ifr_40: "Assumed"
  ifr_45: "Assumed"
  ifr_50: "Assumed"
  ifr_55: "Assumed"
  ifr_60: "Assumed"
  ifr_65: "Assumed"
  ifr_70: "Assumed"